### ISSUE TITLE
Consider adding a take_string method to JsonValue.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [maciejhirsz/json-rust#62]
When parsing JSON data, it can be useful to take certain string values out and place them into variables/structs which will outlive the original data.

It would be nice to have a `fn take_string() -> Option<String>` method which would return `None` if the value wasn't a string and return the inner string, replacing it with `JsonValue::Null`.

Other variants don't need/can't have this as they are Copy.

**Comment by maciejhirsz** [comment]
You mean [like this](https://github.com/maciejhirsz/json-rust/blob/0.9.0/src/value.rs#L221)? ;)

I didn't include it in the release right now, mainly because I became uncertain if this is the best approach for the API to take. An alternative route would be to implement `From<JsonValue>` for `String`, so that you can do:

```rust
let my_string: String = data["foo"].take().into();
```

I'm not sold on that approach yet though, might push `take_string` after all.

**Comment by Mark-Simulacrum** [comment]
Ah, didn't notice that it was included in the code (looked only at the online documentation). That is what I was thinking of.

I don't think the `From<JsonValue>` implementation would work, since it could fail, but [`TryFrom`](https://doc.rust-lang.org/beta/std/convert/trait.TryFrom.html) would (but it's unstable).
I think the main problem with the `take().into()` approach is that it may be confusing to users that you can `into` a `String`, but not the other variants of JSON values.

Side note: I think that code should be simplifiable:
```rust
pub fn take_string(&mut self) -> Option<String> {
    match self {
        JsonValue::String(string) => mem::replace(self, JsonValue::Null),
        _ => None
    }
}
```

**Comment by maciejhirsz** [comment]
Yeah. Getting an explicit `Option<String>` is probably better than doing some implicit casting (such as returning `"null"` if you did take a null.

I simplified the regular `take` (thanks @dtolnay!). This one is tricky though (your code would return `JsonValue` instead of `Option<String>`). You can only extract the `String` from an owned `JsonValue`, so you either do pattern matching twice (check if you have a string -> then replace values -> extract the string) or do the swap -> attempt extract -> swap back on fail. The latter does slightly less work on regular path, which I like.

**Comment by Mark-Simulacrum** [comment]
Ah, yeah, I see what you mean. Trickier than I thought it would be!

**Comment by maciejhirsz** [comment]
Pushed this forward as 0.9 might take a while :)
