### ISSUE TITLE
It's possible to remove the `iterators` module entirely.

### ISSUE THREAD

**Issue by zummenix** [maciejhirsz/json-rust#64]
We can define type aliases for `Members , MembersMut, Entries, EntriesMut`, for example:
```rust
pub type Members<'a> = slice::Iter<'a, JsonValue>;
```
And change methods to return `Option`:
```rust
pub fn members(&self) -> Option<Members>
```
It's a little inconvenient on a call site, but that way we can eliminate one level of indirection.
@maciejhirsz, If you're ok with this I can implement it.

**Comment by maciejhirsz** [comment]
I like the idea of making things faster, though I'd like to think a bit if it can be done without hurting ergonomics. We could return an empty iterator on non array / object types. For non-mutable iterators it can be done by holding an empty `static NO_ENTRIES: &'static [JsonValue] = [];` in the library and returning an iterator for that when `.entries()` is called on non-array value - that preserves the current ergonomics while removing the indirection currently required.

Mutable iterators are more problematic, as static types can't be mutable, but I think a workaround should be possible with unsafe code or RefCell, as you aren't actually enabling any mutation since you don't have any entries. The default `slice::IterMut` allows you to view the underlying slice, which would be dangerous, but that might be solvable with composition - indirection in this case would be just a proxy method, which is something Rust can compile away so it doesn't hurt performance, standard library uses it all over the place.

**Comment by Mark-Simulacrum** [comment]
I've encountered spots where I'm using `.entries()` or `.members()` on something I think is an array/object, but actually isn't -- I think it may be worth considering changing the ergonomics to have the signature be `-> JsonResult<Members, JsonError>` (where the `JsonError` would always be `WrongType`).

This is generally similar to what the user wants and doesn't introduce significant pain into user code (`.unwrap()` if user is sure).

This doesn't really affect the current discussion; it's transparent over what `Members` is (type alias or our own struct), so perhaps I should move this to another issue?

**Comment by maciejhirsz** [comment]
If the fact that you can always get an iterator is causing confusion, then returning an `Option` or `Result` might be better as per @zummenix's suggestion.

**Comment by zummenix** [comment]
@maciejhirsz, I thought about the idea to return an empty iterator, but as @Mark-Simulacrum wrote that user sometimes wants to know `members` exist or not.
I'm not sure about the idea to return `JsonResult`. Other methods (`as_*`) return `Option`.
We can add complement methods that return `JsonResult`, for example with prefix `expect_`

**Comment by Mark-Simulacrum** [comment]
On second thought, I think returning `Option` makes sense: it's not an error to call `members` on a non-array value, but there are no members (`None` is logical).

**Comment by maciejhirsz** [comment]
I think returning `Option<Entries>` and `Option<Members>` respectively might be the best course of action here too. I'd also implement `IntoIter` just for iterating over arrays (since that I'd assume to be the most common case), and since `IntoIter` cannot fail, it can then return an empty iterator for non-array types. How does that sound?

**Comment by maciejhirsz** [comment]
Create an empty mutable iterator with unsafe code ([playground](https://is.gd/gv0hqp)):

```rust
use std::slice;
use std::mem;

enum JsonValue { }

fn get_iter_mut() -> slice::IterMut<'static, JsonValue> {
    let foo = unsafe {
        let ptr: *mut JsonValue = mem::uninitialized();
        slice::from_raw_parts_mut(ptr, 0)
    };
    
    foo.iter_mut()
}

fn main() {
    println!("{}", get_iter_mut().count());
}
```

Instead of using `mem::uninitialized()` it's possible to use `UnsafeCell` to obtain `*mut JsonValue` out of a `&'static [JsonValue]`, thought it shouldn't matter if the pointer actually points anywhere as long as it's hidden behind a custom implementation that doesn't expose [`into_slice`](https://doc.rust-lang.org/std/slice/struct.IterMut.html#method.into_slice), as that would lead to undefined behavior.

**Comment by maciejhirsz** [comment]
Made an [example implementation](https://github.com/maciejhirsz/json-rust/commit/a9def5ccf79331187e4e10a74bbb2ae61792ffc6), need to do the same for `Entries` / `EntriesMut`. All tests passing, empty iterators should be completely safe. The boilerplate should compile away and have no cost penalty over using bare `std::slice::Iter` / `std::slice::IterMut`.

Note: I made it on the 0.8.9 branch as breakage there is limited to changing an enum to a struct, changing the methods to return `Option<T>` is a bigger deal and will have to wait for 0.9.0.

**Comment by zummenix** [comment]
@maciejhirsz, I like your usage of `slice::from_raw_parts_mut`, I thought in the direction of using `Cow` somehow.
I think that changing an enum to a struct is still breaking change since one potentially could use `Some` and `None` variants of the enum.

**Comment by maciejhirsz** [comment]
Yeah, might roll it all out in 0.9.0...

**Comment by zummenix** [comment]
Sorry, I'm a little lost here. What should we do? Should we return options or use your pattern with `slice::from_raw_parts` and return struct?

**Comment by maciejhirsz** [comment]
Sorry if this got a bit chaotic. I'm thinking about two kinda separated but related issues:


##### 1) Returning `Option<Members>` /  `Option<Entries>`
I might want to sleep on this first, making breaking changes isn't very fun, if we do commit to one, then I'd like to make sure it's the right one.

Pros:
- You can easily handle exceptions when the type isn't sure (as per @Mark-Simulacrum's comment).

Cons:
- Bigger breaking change.
- More boiler plate when you don't care about the type, and if you do, you can handle it with `is_array` / `is_object` anyway.

If the main concern here was performance, then empty iterators solve that without changing ergonomics much.

---

##### 2) Implementing `IntoIterator` for arrays

Here empty iterators for non-array types are necessary as `into_iter` _must_ return an `Iterator`:

```rust
let array = array!["foo", true, 42];

for member in array {
    /* ... all good ... */
}
```

```rust
let not_an_array = JsonValue::Null;

for member in not_an_array {
    unreachable!();
}
```

**Comment by Mark-Simulacrum** [comment]
To clarify, in the non-array case of option 2, the iterator returned would be empty, correct?

**Comment by maciejhirsz** [comment]
Yep, it returns a wrapper around `std::slice::Iter`(-`Mut`) constructed from a null pointer and length `0`, so there is no internal pattern matching happening during iteration.

**Comment by maciejhirsz** [comment]
@zummenix now that I'm thinking about it, a slice with length `0` should be safe, no matter what pointer, since you can't mutate it's length. Need to try it out, but if I'm right we can get rid of the wrapper structs and use type aliases as you originally suggested :).

**Comment by Mark-Simulacrum** [comment]
I see the benefits of going with the second option (ergonomics are certainly better, I think). I think the main question here is what we want as a goal of the library: explicit or implicit error handling. Rust seems to prefer explicit error handling, but this library seems to prefer the ergonomics (I think this is a good thing!) over the extremely explicit approach.

I think the cons listed above seem to make option two preferable in this case. `is_array`/`is_object` can be used if someone wants to be explicit (`assert!(json.is_array())`, for example).

**Comment by maciejhirsz** [comment]
Aye, there is Serde if you want idiomatic Rust that parses to structs and all that. I'm not much of a Python person, but I really like [the Zen of Python](https://www.python.org/dev/peps/pep-0020/), relevant lines here:

```
Errors should never pass silently.
Unless explicitly silenced.
```

There are limits to what I'd consider expected behavior, that's why `as_*` methods return `Option<*>` instead of defaulting to `0`. Something like `for foo in data["bar"] {}` when `data` is null simply not doing anything I think is pretty okay.

Also, [all tests passing without wrappers](https://github.com/maciejhirsz/json-rust/commit/010a402f0e1b127c2f07c9c4d6a295008e086f63) :). Need to figure out how to create an empty iterator for `BTreeMap` now.

**Comment by zummenix** [comment]
If question is: What to return from these methods I would stick with `Option`. I like explicitness.
Consider `for v in json.members().unwrap_or([].iter()) {}`.
But I definitely see the point about ergonomics.

**Comment by maciejhirsz** [comment]
Ok.

There is currently no easy way to instantiate a static `BTreeMap`, nor create one from a null pointer. I think `.members()` and `.entries()` should at very least be consistent with one another, and if one of them can't be done with empty iterator trick, then both methods should return an `Option`.

Given that state of affairs, my current goal for 0.9.0 api is:

- `value.members()` -> `Option<Members>` where `Members` is a type alias for `std::slice::Iter`. Analog for mutable.
- `value.entries()` -> `Option<Entries>` where `Entries` is a type alias for `std::collections::btree_map::Iter`. Analog for mutable.
- implement `IntoIterator` for `JsonValue` that returns `Members`, automatically creating empty iterator for non-array types.

I probably won't have time to do much with that till Thursday.

**Comment by zummenix** [comment]
Ok, I'll implement these.

**Comment by maciejhirsz** [comment]
Thanks for the PR!

**Comment by maciejhirsz** [comment]
This issue is already closed, but things have changed a lot in the last few days, so I owe you guys an update:

Since the new Object type has been added, it's now possible to cheaply construct an empty iterator for both arrays and objects. The API will thus remain unchanged there, while having all the performance benefits of removing the extra indirection layer.
