### ISSUE TITLE
Move tests from `tests/lib.rs` to separate files.

### ISSUE THREAD

**Issue by zummenix** [maciejhirsz/json-rust#69]
I noticed that `tests/lib.rs` contains several modules.
- Internals of `unit` can be moved to `tests/unit.rs`
- Internals of `json_checker_fail` can be moved to `tests/checker_fail.rs`
- Internals of `json_checker_pass` can be moved to `tests/checker_pass.rs`

**Comment by maciejhirsz** [comment]
Aye. I want to reorganize more things. It would be nice to move the whole project into a folder in the repo, then move the benchmarks from the `benches` branch to `master`.

**Comment by zummenix** [comment]
> It would be nice to move the whole project into a folder in the repo
Sorry, I didn't understand you. It's seems fine to me where things are now, i.e. in `src` and `tests` folders.

**Comment by maciejhirsz** [comment]
I'll rearrange things myself when I have the time :).

The problem is that benches require a nightly build, and I want to pull some dependencies with them to see how well I perform, and last I tried that kinda breaks the build on stable, so ideally I'd have the json-rust and benchmarks be separate projects in their own folders within the repo.
